"""Config loading, validation, and template generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from pydantic import ValidationError

from watchflow import ConfigError
from watchflow.config.schema import GlobalConfig

_EXAMPLE_TEMPLATE = """\
# WatchFlow configuration — generated by: watchflow init
# Reference: https://github.com/watchflow/watchflow
#
# project: {project_name}

cooldown_ms: 1000
max_concurrent_pipelines: 4

# ── Watchers ────────────────────────────────────────────────────────────────
# Each watcher monitors one or more paths for filesystem changes.

watchers:
  - name: source_watcher
    paths:
      - src/
    patterns:
      - "*.py"
    ignore:
      - "__pycache__"
      - "*.pyc"
      - ".git"
    debounce_ms: 500
    recursive: true
    hash_check: false   # Set true to skip duplicate events for unchanged files

# ── Pipelines ───────────────────────────────────────────────────────────────
# Pipelines define ordered command graphs executed when an intent is matched.
# Use depends_on to express dependency ordering; independent commands run in
# parallel within the same generation.

pipelines:
  - name: run_tests
    fail_fast: true
    total_timeout: 120
    commands:
      - name: lint
        cmd: "ruff check {{changed_file}}"
        timeout: 30
        retry: 1
        retry_strategy: exponential  # linear | exponential | immediate
      - name: test
        cmd: "pytest tests/ -x -q"
        timeout: 90
        depends_on:
          - lint

# ── Intent Rules ────────────────────────────────────────────────────────────
# Rules map filename patterns → pipelines using confidence scoring.
# Built-in rules cover common cases; add your own to override or extend.

intent_rules:
  - name: run_tests
    patterns:
      - "*.py"
      - "test_*.py"
    pipeline: run_tests
    confidence_threshold: 0.7
"""


def load_config(path: Path) -> GlobalConfig:
    """Load and validate a YAML config file, returning a :class:`GlobalConfig`."""
    try:
        raw = path.read_text(encoding="utf-8")
        data: Any = yaml.safe_load(raw)
    except OSError as exc:
        raise ConfigError(f"Cannot read config file: {path}") from exc
    except yaml.YAMLError as exc:
        raise ConfigError(f"YAML parse error in {path}: {exc}") from exc

    if data is None:
        data = {}

    return validate_config(data, source=str(path))


def validate_config(data: dict[str, Any], source: str = "<dict>") -> GlobalConfig:
    """Validate a raw dict against :class:`GlobalConfig`; raise :exc:`ConfigError` on failure."""
    try:
        return GlobalConfig.model_validate(data)
    except ValidationError as exc:
        raise ConfigError(f"Config validation failed ({source}):\n{exc}") from exc


def generate_example_config(project_name: str = "my-project") -> str:
    """Return the contents of an example watchflow.yaml for *project_name*."""
    return _EXAMPLE_TEMPLATE.format(project_name=project_name)
